### ISSUE TITLE
GBNNSIP API for NNSS website not responding

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/GBNNSIP#1]
I can’t get a response from the server using these links at the moment and the NNSS web page is not displaying factsheets etc. 
Please can you check whether it is working or whether it is just my connection?

http://www.brc.ac.uk/gbnnsip/api/Species?idspecies=1001
http://www.brc.ac.uk/gbnnsip/api/Factsheet/1001

**Comment by BirenRathod** [comment]
@StephRorke 
Following steps have been taken.
1. .Net library have been upgraded.
2. Code in SpeciesRepository.cs has been amended now.

You could search by using this URL -> http://www.brc.ac.uk/gbnnsip/api/Species?idspecies=1001 or http://www.brc.ac.uk/gbnnsip/api/Species/1001

Search facility also allow Latin name to search e.g. http://www.brc.ac.uk/gbnnsip/api/Species/branta

I'm closing this issue now. If find any problem you can re-open it.

**Comment by StephRorke** [comment]
Hi Biren - we have the same issues again - please can you check and fix the services if required? Thanks

**Comment by BirenRathod** [comment]
@StephRorke 

It is back now, seems like temporary down.

**Comment by StephRorke** [comment]
@BirenRathod I can not get the search facility to respond on the GBNNSIP, nor when I try the api, please can you have a look into this? Thanks

**Comment by BirenRathod** [comment]
@StephRorke 
Might be server is too busy. It works ok.

**Comment by StephRorke** [comment]
@BirenRathod - yes it was working again by mid afternoon but was unfortunately down for a couple of hours.

**Comment by BirenRathod** [comment]
May be network glitch. I checked server was running fine.

**Comment by BirenRathod** [comment]
@StephRorke  please if resolved.
