### ISSUE TITLE
Photo checker GBNNSIP alert page records not being displayed

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/GBNNSIP#4]
@BirenRathod  This is an issue from July 2018 that has still not been resolved: I am having problems with the photochecker report again (https://www.brc.ac.uk/gbnnsip/photo-check?group_id=1178&implicit=), I am masquerading as Lucy and despite there being a count, the records are not displaying - can this be fixed please e.g.
![image](https://user-images.githubusercontent.com/35227065/49088653-a0de5c00-f251-11e8-9d22-59a27da62420.png). It was identified by John van Breda that a chunk of configuration from the page's edit tab has gone missing (the template for the report output columns) and he says it would be easier if we can ask Biren to recover a backup of the database if we know when it last worked (roughly). 

I do not have an immediate requirement for this but would like it to be functioning correctly by the end of January 2019 please.

**Comment by BirenRathod** [comment]
@StephRorke 

Please ask John to re-configure that page. I tried to restore the backup but I haven't found and the confusion is, we do not sure which backup is require? Also, to get backup is difficult too as CCS use the third party backup management.

**Comment by StephRorke** [comment]
@BirenRathod OK- will do. Thanks for the update
