### ISSUE TITLE
Unable to access native range image folder

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/GBNNSIP#6]
@BirenRathod this location seems not to be available http://www.brc.ac.uk/gbnnsip/api/images/nativerange/NativeRangeThumbnail_NHMSYS0000455529.png/NativeRangeThumbnail_NHMSYS0000455529.png 
I would like to progress the native range maps so they can be displayed on the portal but am not able get a response from the native range api pages nor view the ArcGIS maps. Please can you advise?

**Comment by BirenRathod** [comment]
@StephRorke 
I copied that file in to same folder. So you can access via this URL -> http://www.brc.ac.uk/gbnnsip/api/images/nativerange/NativeRangeThumbnail_NHMSYS0000455529.png

**Comment by BirenRathod** [comment]
@StephRorke please close this if resolved.
