### ISSUE TITLE
 api native range map link not working

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/GBNNSIP#7]
I am receiving an error from the following service: http://www.brc.ac.uk/gbnnsip/api/gbnnNative?idspecies=7. This is required so the NNSS portal native range maps can be displayed asap.

As per your email of 07/02/2018 to Jon Yates at FERA I believe this was a replacement address for http://www.brc.ac.uk/gbnnsip/api/gbnnMap?idspecies=7 however this one still appears to work but is no longer linked from the website.

**Comment by BirenRathod** [comment]
@StephRorke 
As I mentioned, I'm implementing a code for gbnnNative?idspecies=7 . The second link is for our reference to check the map service is still active or not.

**Comment by StephRorke** [comment]
@BirenRathod Please could you give me an idea of when this code fix will be implemented? We have a meeting next week (Tuesday 15th Jan) and it would be ideal if it can be fixed ahead of that - if you could give me an update that would be great - thanks.

**Comment by BirenRathod** [comment]
@StephRorke , I will update on this in couple of days time. Almost half way, so will be finishing soon.

**Comment by StephRorke** [comment]
@BirenRathod - thanks!

**Comment by StephRorke** [comment]
@BirenRathod please can you let me know how you are getting on with this? We have a meeting next Tuesday (15th) and it would be good to be able to give an update. Thanks

**Comment by BirenRathod** [comment]
I'm currently working on it, I have worked yesterday as well and trying to resolve this problem.

**Comment by BirenRathod** [comment]
Hello @StephRorke 
The native range has been implemented this morning. At present some countries like Australia does show coloured layer but hidden if windows size resize due to small screen.

**Comment by StephRorke** [comment]
Hi @BirenRathod 
Thank you for the update - unfortunately I can not see species_iD = 7 with a coloured Australia even at full screen size. I have emptied my cache etc. is there anything else that I should do to ensure I am looking at the most up to date page? Thanks

**Comment by BirenRathod** [comment]
@StephRorke 
Sorry for taking bit long as I found that ArcGIS server was failing to comply with security. You should able to see now the coloured layer.

**Comment by StephRorke** [comment]
@BirenRathod I have now checked species_id = 7 and can see that it is working correctly for this species, however I have noticed issues with the next two I  checked.
Please see http://www.brc.ac.uk/gbnnsip/api/gbnnNative?idspecies=101 which has a native range of 'China South East perimeter' this was one of the new regions created so the native range maps could be more precise, but it seems the new region is not available. It seems that all new regions are not displaying. e.g. http://www.brc.ac.uk/gbnnsip/api/gbnnNative?idspecies=3809. Is it possible to replace the layer?
Also http://www.brc.ac.uk/gbnnsip/api/gbnnNative?idspecies=125 has native regions in Caucasus and Iran, but if you see the map, Iran is not coloured but a North-West region of India is. Can we check the keys are linking correctly?
Thank you.

**Comment by BirenRathod** [comment]
@StephRorke 

You have created a new region in GBNN database but that doesn't mean layer is available in the map layer.

**Comment by StephRorke** [comment]
@BirenRathod I am certain that the layer file was shared with you in late 2017 when we were working on creating the native range maps, please see emails from 03/10/2017 when I emailed an updated shapefile to you, the email trail suggests it was uploaded and later tested and confirmed working. To rectify the issue we have now, please could you let me know what you need from me to allow up to date native range maps using the new regions via the api? Thank you

**Comment by BirenRathod** [comment]
@StephRorke

I updated code now. This means most layers will display on basis of correctly allocated region_id.  You need to make sure that native_range table should have correct region_id. 
Now in this http://www.brc.ac.uk/gbnnsip/api/gbnnNative?idspecies=125 case, country Iran using region_id 285, which is the object_id of other country in new layer, so I suggest, implement the region_id in the region table with its id_parent=34.
Also, please check if any map has still got problem, if it is that means, layer still uses object_id.

**Comment by StephRorke** [comment]
@BirenRathod Thanks  - I will take a look at this on Monday when I am back in the office.

**Comment by BirenRathod** [comment]
Ok.

**Comment by StephRorke** [comment]
@BirenRathod I am receiving an error page for the native range maps: 
![image](https://user-images.githubusercontent.com/35227065/52205806-3d376700-2870-11e9-9787-5b32fa16166e.png)
The database holds the region_id alongside the species_id in the native_range table. Please can you confirm which codes the map is pulling from the database?
Thanks

**Comment by BirenRathod** [comment]
@StephRorke 
I don't see any problem from my browser. that was due to old cached. could you clear the cache and see if it works.

**Comment by StephRorke** [comment]
Thank you @BirenRathod that is working for me now and seems to be picking up on the new regions, I will test a few more species. Is there a way of disabling /minimising the export window? I know this will be asked!
![image](https://user-images.githubusercontent.com/35227065/52206892-8b9a3500-2873-11e9-88a7-319970ee5666.png)

**Comment by BirenRathod** [comment]
@StephRorke 
As I mentioned above any region which linked with object_id, you need to replace with their region_id which has stored in the region table as parent_id. Iran is another example.

**Comment by BirenRathod** [comment]
@StephRorke 

Ignore what I mentioned above. When I checked all regions (countries) of species_id=1562, I found that none of the object_ids or region ids have matched in new layer. That means you need to update all those region_ids in region table. Just in case, if you still confused, here is a shape file copied in this -> W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\__Aliens\gbnnData.zip folder.

**Comment by StephRorke** [comment]
@BirenRathod 
I think if we change the filtering to use the following criteria we should display the correct countries coloured: 

Obtain list of region_id, rt_id and object_id for given species from GBNN_V3 database: e.g. 
SELECT N.SPECIES_ID, N.REGION_ID, R.RT_ID, R.NAME, R.OBJECT_ID
FROM NATIVE_RANGE N 
JOIN REGION R ON N.REGION_ID = R.REGION_ID
WHERE N.SPECIES_ID = 1562

If  GBNN_V3.REGION.RT_ID = 1 use GBNN_V3.NATIVERANGE.REGION_ID to match to Level_1_Co in shape file
If GBNN_V3.REGION.RT_ID = 2 use GBNN_V3.NATIVERANGE.REGION_ID to match to Level_2_Re in shape file
GBNN_V3.REGION.RT_ID >2 use GBNN_V3.REGION.OBJECT_ID to match to Object_ID in shape file

In some cases species region lists will contain a mix of rt_id regions.
Hopefully this will make sense and allow for future additions without causing errors.

**Comment by BirenRathod** [comment]
@StephRorke 
Yes, this make more sense to clearly extract data but that means more probability to play around with code. Anyway, I have implemented the code now. I think results are much more clean then before. I checked below species now. 
http://www.brc.ac.uk/gbnnsip/api/gbnnNative/101
http://www.brc.ac.uk/gbnnsip/api/gbnnNative/125
http://www.brc.ac.uk/gbnnsip/api/gbnnNative/1562
http://www.brc.ac.uk/gbnnsip/api/gbnnNative/3809

**Comment by StephRorke** [comment]
Thanks @BirenRathod  , this looks promising. Did you make any changes to the logic I suggested above? If so please let me know what was changed so I have a good understanding of how the maps should present when I am either creating or checking them.

**Comment by BirenRathod** [comment]
Yes, I have used that logic using RT_ID column to extract data. In terms of mapping, logic is not exactly like that but it covers most of it. One of the critical thing I need to consider is that if there are more than one rows with all three areas (like rt_id=1,2 or >2) then map should come with result to display all.

**Comment by BirenRathod** [comment]
@StephRorke please close this too if resolved.
