### ISSUE TITLE
Species name search facility not working correctly

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/GBNNSIP#8]
@BirenRathod When using the search facility on http://www.nonnativespecies.org/factsheet/index.cfm,  it appears that partial names e.g. hogweed (Giant hogweed), Harmonia (Harmonia axyridis) will return matching entries but when the full name is entered the result is an error message: 
"We're sorry but the Non-native Species Information Portal has unexpectedly returned an error. Please try your search again or alternatively email nnss@fera.gsi.gov.uk "

The search needs to return case insensitive matches for part and whole names.

**Comment by BirenRathod** [comment]
@StephRorke 

The code has been now implemented. That means search should now accepted with space in species name.
